### ISSUE TITLE
Update to latest lzma sdk?

### ISSUE THREAD

**Issue by pwallner** [upx/upx-lzma-sdk#1]
Acc. to [Lzma SDK](http://www.7-zip.de/sdk.html) the actual version is 16.04. UPX uses v4.43. Do you plan an update and if not, are there any disadvantages?

**Comment by markus-oberhumer** [comment]
Duplicate - see the issue in the upx repo.

**Comment by jrn** [comment]
Which issue do you mean? I didn't find an obvious candidate at https://github.com/upx/upx/issues?q=LZMA+SDK.
